import type { Roadmap } from "@/entities/roadmap";

export const mockRoadmaps: Roadmap[] = [
  {
    id: "rm-frontend-core",
    title: "Frontend Core 2026",
    description:
      "От базового HTML/CSS до production React: архитектура, производительность и тестирование.",
    category: "Frontend",
    tags: ["react", "typescript", "css"],
    author: "metacode-team",
    createdAt: "2026-01-15T11:00:00.000Z",
    isPublic: true,
    upvotes: 221,
    isUpvoted: false,
    isFavorited: true,
    nodes: [
      {
        id: "n-html-css",
        title: "HTML + CSS foundations",
        description: "Семантика, a11y, flex/grid, адаптив.",
        parentId: null,
        tasks: [
          {
            id: "t-mdn-layout",
            title: "Layout guide",
            description: "Пройти MDN по Grid/Flex и собрать 2 макета",
            isCompleted: true,
            externalUrl: "https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout",
          },
          {
            id: "t-a11y",
            title: "A11y checklist",
            description: "Проверить формы и контраст в демо-проекте",
            isCompleted: false,
          },
        ],
      },
      {
        id: "n-react",
        title: "React + State",
        description: "Hooks, rendering model, state management.",
        parentId: "n-html-css",
        tasks: [
          {
            id: "t-react-docs",
            title: "Read React docs",
            description: "Обновить знания по useEffect/useMemo",
            isCompleted: false,
            externalUrl: "https://react.dev/learn",
          },
          {
            id: "t-leetcode-frontend",
            title: "LeetCode warmup",
            description: "2 задачи на массивы и строки",
            isCompleted: false,
            externalUrl: "https://leetcode.com/problemset/",
          },
        ],
      },
    ],
  },
  {
    id: "rm-backend-starter",
    title: "Backend Starter Path",
    description: "HTTP, базы данных, кеш и наблюдаемость для junior/middle backend.",
    category: "Backend",
    tags: ["api", "sql", "redis"],
    author: "alex_dev",
    createdAt: "2026-02-03T09:40:00.000Z",
    isPublic: true,
    upvotes: 156,
    isUpvoted: false,
    isFavorited: false,
    nodes: [
      {
        id: "n-http",
        title: "HTTP & REST",
        description: "Методы, коды ответа, idempotency.",
        parentId: null,
        tasks: [
          {
            id: "t-http-rfc",
            title: "Read RFC summary",
            description: "Повторить caching headers и conditional requests",
            isCompleted: false,
          },
        ],
      },
      {
        id: "n-sql",
        title: "PostgreSQL",
        description: "Нормализация, индексы, explain analyze.",
        parentId: "n-http",
        tasks: [
          {
            id: "t-sql-index",
            title: "Index tuning",
            description: "Сравнить планы запросов до/после индекса",
            isCompleted: true,
          },
        ],
      },
    ],
  },
  {
    id: "rm-leetcode-75",
    title: "LeetCode 75 Sprint",
    description: "Практика по списку LeetCode 75, с акцентом на patterns.",
    category: "Algorithms",
    tags: ["leetcode", "dsa", "interview"],
    author: "leet_solver",
    createdAt: "2026-02-12T12:10:00.000Z",
    isPublic: true,
    upvotes: 340,
    isUpvoted: true,
    isFavorited: true,
    nodes: [
      {
        id: "n-array-two-pointers",
        title: "Arrays & Two pointers",
        description: "Two Sum, Container With Most Water, 3Sum.",
        parentId: null,
        tasks: [
          {
            id: "t-two-sum",
            title: "Two Sum",
            description: "Решить и записать 2 подхода",
            isCompleted: true,
            externalUrl: "https://leetcode.com/problems/two-sum/",
          },
          {
            id: "t-container",
            title: "Container With Most Water",
            description: "Оптимизировать до O(n)",
            isCompleted: false,
            externalUrl: "https://leetcode.com/problems/container-with-most-water/",
          },
        ],
      },
      {
        id: "n-dp",
        title: "Dynamic Programming",
        description: "House Robber, Coin Change, LIS.",
        parentId: "n-array-two-pointers",
        tasks: [
          {
            id: "t-house-robber",
            title: "House Robber",
            description: "Сделать top-down и bottom-up",
            isCompleted: false,
            externalUrl: "https://leetcode.com/problems/house-robber/",
          },
        ],
      },
    ],
  },
  {
    id: "rm-system-design",
    title: "System Design Lite",
    description: "Короткий трек по скейлингу, очередям и распределенным системам.",
    category: "Architecture",
    tags: ["system-design", "queues", "scaling"],
    author: "code_master",
    createdAt: "2025-12-28T08:20:00.000Z",
    isPublic: true,
    upvotes: 98,
    isUpvoted: false,
    isFavorited: false,
    nodes: [
      {
        id: "n-cache",
        title: "Caching strategy",
        description: "Cache-aside, write-through, invalidation.",
        parentId: null,
        tasks: [
          {
            id: "t-cache-patterns",
            title: "Patterns review",
            description: "Сравнить latency/consistency trade-offs",
            isCompleted: false,
          },
        ],
      },
    ],
  },
  {
    id: "rm-private-career",
    title: "Private Career Plan",
    description: "Персональная карта роста на 3 месяца.",
    category: "Career",
    tags: ["private", "career"],
    author: "you",
    createdAt: "2026-02-20T16:30:00.000Z",
    isPublic: false,
    upvotes: 0,
    isUpvoted: false,
    isFavorited: true,
    nodes: [
      {
        id: "n-soft-skills",
        title: "Communication",
        description: "Аргументация решений и code review практики.",
        parentId: null,
        tasks: [
          {
            id: "t-review-weekly",
            title: "Weekly review",
            description: "Провести 2 развёрнутых ревью в неделю",
            isCompleted: false,
          },
        ],
      },
    ],
  },
  {
    id: "rm-typing-boost",
    title: "Monkeytype Performance",
    description: "Трек на скорость печати 100+ WPM без потери точности.",
    category: "Productivity",
    tags: ["typing", "monkeytype"],
    author: "typing_champ",
    createdAt: "2026-02-10T07:15:00.000Z",
    isPublic: true,
    upvotes: 67,
    isUpvoted: false,
    isFavorited: false,
    nodes: [
      {
        id: "n-warmup",
        title: "Warmup",
        description: "Ежедневные сессии 15-30-60 секунд.",
        parentId: null,
        tasks: [
          {
            id: "t-monkeytype-60",
            title: "Monkeytype 60s",
            description: "10 прогонов в 60s режиме",
            isCompleted: true,
            externalUrl: "https://monkeytype.com/",
          },
          {
            id: "t-monkeytype-accuracy",
            title: "Accuracy > 96%",
            description: "Стабилизировать точность на длинных сессиях",
            isCompleted: false,
            externalUrl: "https://monkeytype.com/",
          },
        ],
      },
    ],
  },
];
